canton {
  features {
    enable-testing-commands = yes
  }

  participants {
    participant1 {
      storage {
        type = memory
      }
      ledger-api {
        port = 6865
        address = "0.0.0.0"
      }
      admin-api {
        port = 10011
        address = "0.0.0.0"
      }
    }
  }
}
